# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/torrent-tracker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/torrent-tracker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/torrent-tracker/CMakeFiles /home/user/torrent-tracker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/torrent-tracker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named torrent_tracker

# Build rule for target.
torrent_tracker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 torrent_tracker
.PHONY : torrent_tracker

# fast build rule for target.
torrent_tracker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/build
.PHONY : torrent_tracker/fast

HTTPProtocol.o: HTTPProtocol.cpp.o

.PHONY : HTTPProtocol.o

# target to build an object file
HTTPProtocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPProtocol.cpp.o
.PHONY : HTTPProtocol.cpp.o

HTTPProtocol.i: HTTPProtocol.cpp.i

.PHONY : HTTPProtocol.i

# target to preprocess a source file
HTTPProtocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPProtocol.cpp.i
.PHONY : HTTPProtocol.cpp.i

HTTPProtocol.s: HTTPProtocol.cpp.s

.PHONY : HTTPProtocol.s

# target to generate assembly for a file
HTTPProtocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPProtocol.cpp.s
.PHONY : HTTPProtocol.cpp.s

HTTPRequest.o: HTTPRequest.cpp.o

.PHONY : HTTPRequest.o

# target to build an object file
HTTPRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPRequest.cpp.o
.PHONY : HTTPRequest.cpp.o

HTTPRequest.i: HTTPRequest.cpp.i

.PHONY : HTTPRequest.i

# target to preprocess a source file
HTTPRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPRequest.cpp.i
.PHONY : HTTPRequest.cpp.i

HTTPRequest.s: HTTPRequest.cpp.s

.PHONY : HTTPRequest.s

# target to generate assembly for a file
HTTPRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPRequest.cpp.s
.PHONY : HTTPRequest.cpp.s

HTTPResponse.o: HTTPResponse.cpp.o

.PHONY : HTTPResponse.o

# target to build an object file
HTTPResponse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPResponse.cpp.o
.PHONY : HTTPResponse.cpp.o

HTTPResponse.i: HTTPResponse.cpp.i

.PHONY : HTTPResponse.i

# target to preprocess a source file
HTTPResponse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPResponse.cpp.i
.PHONY : HTTPResponse.cpp.i

HTTPResponse.s: HTTPResponse.cpp.s

.PHONY : HTTPResponse.s

# target to generate assembly for a file
HTTPResponse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/HTTPResponse.cpp.s
.PHONY : HTTPResponse.cpp.s

Peer.o: Peer.cpp.o

.PHONY : Peer.o

# target to build an object file
Peer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Peer.cpp.o
.PHONY : Peer.cpp.o

Peer.i: Peer.cpp.i

.PHONY : Peer.i

# target to preprocess a source file
Peer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Peer.cpp.i
.PHONY : Peer.cpp.i

Peer.s: Peer.cpp.s

.PHONY : Peer.s

# target to generate assembly for a file
Peer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Peer.cpp.s
.PHONY : Peer.cpp.s

Repository.o: Repository.cpp.o

.PHONY : Repository.o

# target to build an object file
Repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Repository.cpp.o
.PHONY : Repository.cpp.o

Repository.i: Repository.cpp.i

.PHONY : Repository.i

# target to preprocess a source file
Repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Repository.cpp.i
.PHONY : Repository.cpp.i

Repository.s: Repository.cpp.s

.PHONY : Repository.s

# target to generate assembly for a file
Repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Repository.cpp.s
.PHONY : Repository.cpp.s

RequestParser.o: RequestParser.cpp.o

.PHONY : RequestParser.o

# target to build an object file
RequestParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/RequestParser.cpp.o
.PHONY : RequestParser.cpp.o

RequestParser.i: RequestParser.cpp.i

.PHONY : RequestParser.i

# target to preprocess a source file
RequestParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/RequestParser.cpp.i
.PHONY : RequestParser.cpp.i

RequestParser.s: RequestParser.cpp.s

.PHONY : RequestParser.s

# target to generate assembly for a file
RequestParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/RequestParser.cpp.s
.PHONY : RequestParser.cpp.s

Server.o: Server.cpp.o

.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i

.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s

.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/Server.cpp.s
.PHONY : Server.cpp.s

StringToPrimitivesParser.o: StringToPrimitivesParser.cpp.o

.PHONY : StringToPrimitivesParser.o

# target to build an object file
StringToPrimitivesParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/StringToPrimitivesParser.cpp.o
.PHONY : StringToPrimitivesParser.cpp.o

StringToPrimitivesParser.i: StringToPrimitivesParser.cpp.i

.PHONY : StringToPrimitivesParser.i

# target to preprocess a source file
StringToPrimitivesParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/StringToPrimitivesParser.cpp.i
.PHONY : StringToPrimitivesParser.cpp.i

StringToPrimitivesParser.s: StringToPrimitivesParser.cpp.s

.PHONY : StringToPrimitivesParser.s

# target to generate assembly for a file
StringToPrimitivesParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/StringToPrimitivesParser.cpp.s
.PHONY : StringToPrimitivesParser.cpp.s

TrackerRequest.o: TrackerRequest.cpp.o

.PHONY : TrackerRequest.o

# target to build an object file
TrackerRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/TrackerRequest.cpp.o
.PHONY : TrackerRequest.cpp.o

TrackerRequest.i: TrackerRequest.cpp.i

.PHONY : TrackerRequest.i

# target to preprocess a source file
TrackerRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/TrackerRequest.cpp.i
.PHONY : TrackerRequest.cpp.i

TrackerRequest.s: TrackerRequest.cpp.s

.PHONY : TrackerRequest.s

# target to generate assembly for a file
TrackerRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/TrackerRequest.cpp.s
.PHONY : TrackerRequest.cpp.s

TrackerService.o: TrackerService.cpp.o

.PHONY : TrackerService.o

# target to build an object file
TrackerService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/TrackerService.cpp.o
.PHONY : TrackerService.cpp.o

TrackerService.i: TrackerService.cpp.i

.PHONY : TrackerService.i

# target to preprocess a source file
TrackerService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/TrackerService.cpp.i
.PHONY : TrackerService.cpp.i

TrackerService.s: TrackerService.cpp.s

.PHONY : TrackerService.s

# target to generate assembly for a file
TrackerService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/TrackerService.cpp.s
.PHONY : TrackerService.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torrent_tracker.dir/build.make CMakeFiles/torrent_tracker.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... torrent_tracker"
	@echo "... HTTPProtocol.o"
	@echo "... HTTPProtocol.i"
	@echo "... HTTPProtocol.s"
	@echo "... HTTPRequest.o"
	@echo "... HTTPRequest.i"
	@echo "... HTTPRequest.s"
	@echo "... HTTPResponse.o"
	@echo "... HTTPResponse.i"
	@echo "... HTTPResponse.s"
	@echo "... Peer.o"
	@echo "... Peer.i"
	@echo "... Peer.s"
	@echo "... Repository.o"
	@echo "... Repository.i"
	@echo "... Repository.s"
	@echo "... RequestParser.o"
	@echo "... RequestParser.i"
	@echo "... RequestParser.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... StringToPrimitivesParser.o"
	@echo "... StringToPrimitivesParser.i"
	@echo "... StringToPrimitivesParser.s"
	@echo "... TrackerRequest.o"
	@echo "... TrackerRequest.i"
	@echo "... TrackerRequest.s"
	@echo "... TrackerService.o"
	@echo "... TrackerService.i"
	@echo "... TrackerService.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

